### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by albedoklaus** [albedoklaus/cceesss2020#1]
Warum sieht das diff hier so komisch aus? ee1751d99ed51985c64082d941be1469eddb8166

**Comment by TheProfms** [comment]
Was meinst du?

**Comment by TheProfms** [comment]
Meinst du, weil es anzeigt, dass sich angeblich alles geändert hat? Das kann damit zusammenhängen, dass ich einfach die neue Datei komplett hochgeladen hab und das dann alles als Änderung markiert

**Comment by albedoklaus** [comment]
Ah, ja, das ist eine gute Erklärung :+1:
